os: windows           # Windows 10.0.17134 N/A Build 17134
language: shell       # 'language: python' is an error on Travis CI Windows
before_install:
  - choco install python --version 3.6.8
  - python --version
  - python -m pip install --upgrade pip
env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

script: skip

before_deploy:
  - pip install -r requirements.txt
  - pytest
  - python build.py

deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: 'artifacts/*'
  skip_cleanup: true
  on:
    tags: true
