os: windows           # Windows 10.0.17134 N/A Build 17134
language: shell       # 'language: python' is an error on Travis CI Windows
before_install:
  - choco install python --version 3.6.8
  - python --version
  - python -m pip install --upgrade pip
env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

script: skip

before_deploy:
  - pip install -r requirements.txt
  - python build.py
  - sleep 10
  - dir -l dist

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: TempGen.zip
  skip_cleanup: true
  on:
    tags: true
